service: api-tts
frameworkVersion: '3'

plugins:
 # - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: python3.9
  iamRoleStatements:
    - Effect: Allow
      Action:
        - polly:*
      Resource: "*"
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "*"
  httpApi:
    cors: true

functions:
  health:
    handler: handler.health
    events:
      - httpApi:
          path: /
          method: get
  v1Description:
    handler: handler.v1_description
    events:
      - httpApi:
          path: /v1
          method: get
  v2Description:
    handler: handler.v2_description
    events:
      - httpApi:
          path: /v2
          method: get
  v1tts:
    handler: v1-tts.v1_tts
    events:
      - httpApi:
          path: /v1/tts
          method: post
  v2tts:
    handler: v2-tts.v2_tts
    events:
      - httpApi:
          path: /v2/tts
          method: post
  v3tts:
    handler: v3-tts.v3_tts
    events:
      - httpApi:
          path: /v3/tts
          method: post
